module Websocket
  module Echo
    module Io
      VERSION: String
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides

      class Server
        PORT: Integer

        def self.start: -> void
      end

      class Handler
        GOODBYE_LINE: String
        SHUTDOWN_LINE: String

        def on_message: -> void
        def on_open: -> void
        def on_shutdown: -> void
      end
    end
  end
end
